/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f3f4f3',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'secondary': '#5A6065',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#c69d60',
        'surface-container-highest': '#e2e2e2',
        'on-tertiary-fixed-variant': '#5f410c',
        'on-surface': '#111827',
        'surface-dim': '#dadad9',
        'primary-container': '#1f3a5f',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#1c1b1b',
        'tertiary-container': '#503400',
        'on-primary-fixed-variant': '#2d476d',
        'on-secondary': '#ffffff',
        'surface': '#f9f9f8',
        'tertiary-fixed-dim': '#ecbf7f',
        'inverse-surface': '#2f3130',
        'on-tertiary-fixed': '#281800',
        'outline': '#74777f',
        'surface-container-high': '#e8e8e7',
        'on-background': '#111827',
        'secondary-container': '#e2dfde',
        'surface-tint': '#465f86',
        'primary': '#0a192f',
        'surface-variant': '#e2e2e2',
        'tertiary': '#342000',
        'on-primary-fixed': '#001c3b',
        'error': '#dc2626',
        'outline-variant': '#e5e7eb',
        'surface-bright': '#f9f9f8',
        'background': '#f9f9f8',
        'accent-blue': '#2563eb',
        'beacon-emerald': '#059669',
        'beacon-amber': '#d97706',
        'beacon-crimson': '#dc2626',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        none: '0',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'max-width': '1280px',
        'stack-xl': '120px',
        'stack-lg': '64px',
        'stack-md': '24px',
        'stack-sm': '8px',
        margin: '40px',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        serif: ['Newsreader', 'Instrument Serif', 'serif'],
        display: ['Instrument Serif', 'Newsreader', 'serif'],
        editorial: ['Newsreader', 'serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
